### ISSUE TITLE
If geometry of the agent is a 'Point', there is a broken image shown on the map at that point instead of the specified portrayal.

### ISSUE THREAD

**Issue by mkchimp** [Corvince/mesa-geo#17] opened 2019-09-17 09:17 UTC

**Comment by JHindelang** [comment] 2020-03-03 20:48
Hi mkchimp,
i've got the same probleme. Did you find an solution for your problem so far?

**Comment by applibres** [comment] 2020-04-07 00:10
Hi,
Also the same problem!
How can display points with a specific color/shape?

**Comment by JHindelang** [comment] 2020-04-07 08:41
Hi applibres,

I could fix the problem by making some changes in the LeafletMap.js file. It looked to me like the error was caused by some dlls, that could not be loaded. I’ve attached the code with the changes i made (lines 12-19 and 38-45). You just have to replace it in the directory of your library. With this code it will display circle markers for all points and you can specify the radius and also the color in the portrayal dictionary for the map element of your server.

`var MapModule = function (view, zoom, map_width, map_height) {
  // Create the map tag:
  var map_tag = "<div style='width:" + map_width + "px; height:" + map_height + "px;border:1px dotted' id='mapid'></div>"
  // Append it to body:
  var div = $(map_tag)[0]
  $('#elements').append(div)

  // Create Leaflet map and Agent layers
  var Lmap = L.map('mapid').setView(view, zoom)
  var AgentLayer = L.geoJSON().addTo(Lmap)

  var geojsonMarkerOptions = {
    radius: 2,
    fillColor: "#ff7800",
    color: "#000",
    weight: 1,
    opacity: 1,
    fillOpacity: 0.8
   }
  // create the OSM tile layer with correct attribution
  var osmUrl = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
  var osmAttrib = 'Map data © <a href="http://openstreetmap.org">OpenStreetMap</a> contributors'
  var osm = new L.TileLayer(osmUrl, {minZoom: 0, maxZoom: 18, attribution: osmAttrib})
  Lmap.addLayer(osm)

  this.render = function (data) {
    function PopUpProperties (feature, layer) {
      var popupContent = '<table>'
      if (feature.properties) {
        for (var p in feature.properties) {
          popupContent += '<tr><td>' + p + '</td><td>' + feature.properties[p] + '</td></tr>'
        }
      }
      popupContent += '</table>'
      layer.bindPopup(popupContent)
    }

    AgentLayer.remove()
    console.log(data)
    AgentLayer = L.geoJSON(data, {
    pointToLayer: function (feature, latlng) {
        return L.circleMarker(latlng, {radius:feature.properties.radius, color: feature.properties.color});
    }
    }).addTo(Lmap)
  }

  this.reset = function () {
    Lmap.remove()
    Lmap = L.map('mapid').setView(view, zoom)
    Lmap.addLayer(osm)
  }
}
`
I added the following key-value pairs to the portrayal dictionary:
`portrayal = dict()
portrayal["Shape"] = "Circle"
portrayal["radius"] = "2"
portrayal["x"] = "0"
portrayal["y"] = "0"
portrayal["color"] = "Green"`

I hope this workaround can help you.

Best regards

**Comment by Corvince** [comment] 2020-04-07 16:08
Thanks for the fix @JHindelang! If you can submit a PR for the fix I'll merge it

**Comment by applibres** [comment] 2020-04-07 17:25
Thanks @JHindelang for your answer and code. 
However, even replacing LeafletMap.js file, for me, it is not working yet. Also I have updated server file with portrayal dictionary.
I am using GeoSchelling example, with my own geojson points file. Points are loaded but no displayed (see picture attached). 
![screen01](https://user-images.githubusercontent.com/2652757/78700023-6e735300-78ca-11ea-901b-ca4381dd253f.png)

I get this messages from console:
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 1.51ms
WARNING:tornado.access:404 GET /static/css/images/marker-icon.png (127.0.0.1) 0.80ms
WARNING:tornado.access:404 GET /static/css/images/marker-icon-2x.png (127.0.0.1) 0.78ms
WARNING:tornado.access:404 GET /static/css/images/marker-shadow.png (127.0.0.1) 0.70ms

I can not find the place where those images are located in my machine.

Please, any idea is welcome!
Thanks .

**Comment by JHindelang** [comment] 2020-04-07 18:00
Did you replace the file in the environemnt that you are currently using? For me it worked this way. 
The changes in the LeafletMap.js avoid that the server tries to display icons from the files, that you can not load. I would guess that the original LeafletMap.js is still used. 

Anywas, it looks to me like the GeoSchelling example is not made for points. You should use this with shapes like polygons and multipolygons.

**Comment by applibres** [comment] 2020-04-09 00:10
Thanks again, I got it! 
For the record:
1) I have edited and updated (not changed) the file LeafletMap.js (according your code) in the enviroment configuration directory located into "/anaconda3/envs/_nameofenv_/lib/python3.7/site-packages/mesa_geo/visualization/templates/js/"
[LeafletMap-updated.js.txt](https://github.com/Corvince/mesa-geo/files/4453337/LeafletMap-updated.js.txt)
2) Added the key-value pairs to the portrayal dictionary in the server file.
3) Delete history and cookies in the browser
4) Reload the server (python ./server.py)

**Comment by glicerico** [comment] 2020-04-21 10:44
Thanks @JHindelang and @applibres, I created a separate PersonAgent class for my mobile agents on the map, and managed to make the points display properly with your workaround, as well as the Neighbourhood patches. I am updating the color of the PersonAgent properly, but I am unable to update the color of the Neighhbourhood (polygon) agents in the map. Something seems to have broken. 
Do you know if the method you suggested doesn't deactivate the color update of the patches?

**Comment by applibres** [comment] 2020-04-21 18:37
Hi, @glicerico :
Remember that in file LeafletMap.js we modified the AgentLayer variable:
```
    AgentLayer.remove()
    console.log(data)
    //AgentLayer = L.geoJSON(data, {
      //onEachFeature: PopUpProperties,
      //style: function (feature) {
        //return {color: feature.properties.color}
      //}
    //}).addTo(Lmap)
    AgentLayer = L.geoJSON(data, {
    onEachFeature: PopUpProperties,  
    pointToLayer: function (feature, latlng) {
        return L.circleMarker(latlng, {radius:feature.properties.radius, color: feature.properties.color});
    }
    }).addTo(Lmap)   
  }
```
I am not complete sure if that is the reason, but probably you need to check it.

**Comment by glicerico** [comment] 2020-04-22 04:16
Thanks @applibres , yes I suspect that is the problem, but don't know enough about how the layers work to understand how to fix it. Any guidance is appreciated :)

**Comment by Corvince** [comment] 2020-04-22 04:59
I am in mobile so I can't check right now, but can you try to readd the `style` lines to the `L.geoJSON` function? (copy below and remove the `//`)

**Comment by glicerico** [comment] 2020-04-22 05:50
Yeah, I tried that before and it stopped the whole map from being displayed (just confirmed again, just in case).
After digging a bit more, it seems to me that the agent layer can only handle one type of geometry... see examples [here](https://leafletjs.com/examples/quick-start/) on how they add different layers for different geometries.
So, I am wondering if a separate render method is needed in MapModule for the polygons and for the  Points.

**Comment by Corvince** [comment] 2020-04-22 09:48
I See, that makes sense. I don't have much time right now to work on this, but if you could come up with a minimal working example that would be super useful

**Comment by glicerico** [comment] 2020-04-23 03:57
@Corvince , you were right, but I missed adding a comma when I uncommented the `style` code, and that's why it wasn't showing the map. So, fixed now. I'll submit a PR that handles both the Points and Polygons.

**Comment by glicerico** [comment] 2020-04-23 06:03
I am implementing a simple SIR epidemics model that will show the modification to the portrayal dictionary also suggested above. When ready, I will submit a PR to have it as a second use-case for mesa-geo.

**Comment by glicerico** [comment] 2020-04-24 08:00
Btw, I think this issue can be closed @Corvince

**Closed** 2020-05-11 07:56 UTC
